# SMSEagle SMS Gateway

OpenNMS configuration module to support monitoring for SMSEagle SMS Gateway devices.
The configuration adds capabilities for performance data collection for the following metrics:

- GSM Signal
- Inbox and outbox folder
- Folder statistics for sent last 24h, last minute and errors in last 24h

## Requirements

- SMSEagle SMS Gateway
- Tested with NXS-9700

## Download the configuration package

.Download the configuration files
[source, bash]
----
mkdir /tmp
cd /tmp
curl -L https://github.com/opennms-config-modules/smseagle-gateway/archive/1.0.tar.gz | tar xz
cd smseagle-gateway-1.0
----
cd
----

## Enable performance data collection

[source, bash]
----
cp datacollection/smseagle.xml ${OPENNMS_HOME}/etc/datacollection
----

.Add include statement in alphabetical order in ${OPENNMS_HOME}/etc/datacollection-config.xml
[source, bash]
----
<include-collection dataCollectionGroup="SMSEagle"/>
----

## Add performance graphs

[source, bash]
----
cp snmp-graph.properties.d/smseagle-graph.properties ${OPENNMS_HOME}/etc/snmp-graph.properties.d/
----

# License & Authors

- Author:: Ronny Trommer <ronny@opennms.org>

Licensed under the GNU Affero General Public License 3+. You may obtain a copy of the License at http://www.gnu.org/licenses/agpl-3.0.html.
